### ISSUE TITLE
Video compression with example files throwing errors

### ISSUE THREAD

**Issue by Abhishek935** [ver228/tierpsy-tracker#72]
Hi,  I am testing tierspy using your example files. I have Python 3.6 and Mac Mojave. I keep getting the following error. Please help.

Capture_Ch1_18062015_140908 Assigning trajectories. Total time = 0:00:04, fps = 306.8; Frame 1000 of 1208
ERROR: 
AttributeError: 'DataFrame' object has no attribute 'ix'
/Users/abhishek/anaconda3/envs/tierpsy/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning:numpy.ufunc size changed, may indicate binary incompatibility. Expected 216, got 192
/Users/abhishek/anaconda3/envs/tierpsy/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning:numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
/Users/abhishek/anaconda3/envs/tierpsy/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning:numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
/Users/abhishek/anaconda3/envs/tierpsy/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning:numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
/Users/abhishek/anaconda3/envs/tierpsy/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning:numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
/Users/abhishek/anaconda3/envs/tierpsy/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning:numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
/Users/abhishek/anaconda3/envs/tierpsy/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning:numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
Traceback (most recent call last):
  File "/Users/abhishek/anaconda3/envs/tierpsy/lib/python3.6/site-packages/tierpsy/processing/ProcessWorker.py", line 108, in <module>
    ProcessWorker(**args, cmd_original = subprocess.list2cmdline(sys.argv))
  File "/Users/abhishek/anaconda3/envs/tierpsy/lib/python3.6/site-packages/tierpsy/processing/ProcessWorker.py", line 38, in __init__
    self.execAllPoints()
  File "/Users/abhishek/anaconda3/envs/tierpsy/lib/python3.6/site-packages/tierpsy/processing/ProcessWorker.py", line 66, in execAllPoints
    cmd_original = self.cmd_original)
  File "/Users/abhishek/anaconda3/envs/tierpsy/lib/python3.6/site-packages/tierpsy/processing/trackProvenance.py", line 28, in execThisPoint
    func(**argkws)
  File "/Users/abhishek/anaconda3/envs/tierpsy/lib/python3.6/site-packages/tierpsy/analysis/traj_join/joinBlobsTrajectories.py", line 390, in joinBlobsTrajectories
    joinGapsTrajectories(trajectories_file, min_track_size, max_frames_gap, area_ratio_lim)
  File "/Users/abhishek/anaconda3/envs/tierpsy/lib/python3.6/site-packages/tierpsy/analysis/traj_join/joinBlobsTrajectories.py", line 254, in joinGapsTrajectories
    area_ratio_lim=area_ratio_lim
  File "/Users/abhishek/anaconda3/envs/tierpsy/lib/python3.6/site-packages/tierpsy/analysis/traj_join/joinBlobsTrajectories.py", line 364, in joinGapsTrajectoriesDF
    relations_dict, valid_indexes = _findNextTraj(plate_worms, area_ratio_lim, min_track_size, max_frames_gap)
  File "/Users/abhishek/anaconda3/envs/tierpsy/lib/python3.6/site-packages/tierpsy/analysis/traj_join/joinBlobsTrajectories.py", line 303, in _findNextTraj
    first_rows = df.ix[tracks_data['frame_number']['argmin'].values]
  File "/Users/abhishek/anaconda3/envs/tierpsy/lib/python3.6/site-packages/pandas/core/generic.py", line 5273, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'ix'
'/Users/abhishek/anaconda3/envs/tierpsy/bin/python' '/Users/abhishek/anaconda3/envs/tierpsy/lib/python3.6/site-packages/tierpsy/processing/ProcessWorker.py' '/Users/abhishek/Downloads/example_data/multiworm/Capture_Ch1_18062015_140908.mov' --masks_dir '/Users/abhishek/Tmp/MaskedVideos/' --results_dir '/Users/abhishek/Tmp/Results/' --json_file '/Users/abhishek/anaconda3/envs/tierpsy/lib/python3.6/site-packages/tierpsy/extras/param_files/MULTIWORM_OPENWORM.json' --analysis_checkpoints 'TRAJ_JOIN' 'SKE_INIT' 'BLOB_FEATS' 'SKE_CREATE' 'SKE_FILT' 'SKE_ORIENT' 'INT_PROFILE' 'INT_SKE_ORIENT' 'FEAT_CREATE'
*************************************************
Tasks: 1 finished, 0 remaining. Total_time 0:00:10.
*************************************************

**Comment by ver228** [comment]
It seems the error is due to a deprecation error. The version 1.0 of pandas deprecated some expressions (https://stackoverflow.com/questions/59991397/attributeerror-dataframe-object-has-no-attribute-ix). The error should corrected in the current HEAD version in our repo. However, it is not yet uploaded to conda-forge.

In the meanwhile, I recommend you to downgrade pandas to `conda install pandas=0.25`. This should solve the problem.
